name: Auto PR para branches codex/*

on:
  push:
    branches:
      - 'codex/**'           # dispara em push nas codex/*
  create:                     # se alguém só "criar" a branch (alguns clientes fazem isso)
  workflow_dispatch:          # permite rodar manualmente pela aba Actions

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  open-pr:
    if: startsWith(github.ref, 'refs/heads/codex/')  # garante que só roda para codex/*
    runs-on: ubuntu-latest
    steps:
      - name: Abrir (ou reaproveitar) PR para desenvolvimento
        id: pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const base = 'desenvolvimento';
            const head = context.ref.replace('refs/heads/',''); // ex: codex/xyz
            const { owner, repo } = context.repo;

            // já existe PR aberto?
            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${head}`, base
            });
            if (prs.length) {
              core.notice(`PR já existe: #${prs[0].number}`);
              core.setOutput('number', prs[0].number);
              return;
            }

            const title = `Codex: ${head}`;
            const body  = `PR automático criado para **${head}** → **${base}**.`;

            const { data: pr } = await github.rest.pulls.create({
              owner, repo, title, head, base, body, draft: false
            });
            core.notice(`PR criado: #${pr.number}`);
            core.setOutput('number', pr.number);
