
name: P처s-merge PR (Maven)

on:
  pull_request:
    types: [closed]            # dispara quando o PR for fechado
    branches: [ desenvolvimento ]   # <-- altere se sua branch alvo tiver outro nome

jobs:
  run-class:
    if: github.event.pull_request.merged == true   # garante que foi MESCLADO (e n찾o s처 fechado)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c처digo do merge
        uses: actions/checkout@v4
        with:
          # usa o commit de merge que o GitHub criou
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      - name: Executar classe Java via Maven
        run: |
          if [ -f ./mvnw ]; then MVN=./mvnw; else MVN=mvn; fi
          $MVN -B -ntp -U -DskipTests exec:java \
            -Dexec.mainClass=test.UsuarioControllerTest \
